apiVersion: v2
name: keycloak
version: 18.10.0
appVersion: 17.0.1-legacy
description: Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
sources:
  - https://github.com/open-cloud-initiative/charts
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
maintainers:
  - name: katallaxie
    email: sebastian@katallaxie.dev
dependencies:
  - name: cnpg/cluster
    version: 0.3.1
    repository: https://cloudnative-pg.github.io/charts
    condition: postgresql.enabled