name: publish

on:
  push:
    branches: [ main, release/* ]
    paths:
      - "staging/**"
      - "stable/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  charts:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@v3
      - uses: jimmidyson/asdf-parse-tool-versions@v2
        id: versions
      - env:
          HELM_VERSION: ${{ fromJson(steps.versions.outputs.tools).helm }}
          HELM_CT_VERSION: ${{ fromJson(steps.versions.outputs.tools).helm-ct  }}
        run: |
          asdf global helm $HELM_VERSION
          asdf global helm-ct $HELM_CT_VERSION
      - run: make publish
        env:
          COMMIT_EMAIL: "no-reply@zeiss.com"
          COMMIT_USERNAME: "ZEISS CI"
          GIT_REMOTE_URL: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zeiss/charts.git"